<a href="https://colab.research.google.com/github/ghziirmdhn/Tugas-Metode-Numerik/blob/main/Pengaplikasian_Sistem_Persamaan_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

def inverse_matrix_method(A):
    # Periksa apakah A persegi
    if A.shape[0] != A.shape[1]:
        print("Error: Matriks input tidak persegi.")
        return None

    # Hitung determinan
    det = np.linalg.det(A)

    # Periksa apakah determinan nol (matriks tak dapat diinvert)
    if np.isclose(det, 0):
        print("Error: Matriks singular (tidak dapat diinvert).")
        return None

    # Hitung invers
    A_inv = np.linalg.inv(A)

    return A_inv

# Contoh penggunaan:
A = np.array([[2, 1, 3],
              [0, -1, 4],
              [5, 2, 1]])

A_inv = inverse_matrix_method(A)
if A_inv is not None:
    print("Invers dari A:")
    print(A_inv)


Invers dari A:
[[-0.52941176  0.29411765  0.41176471]
 [ 1.17647059 -0.76470588 -0.47058824]
 [ 0.29411765  0.05882353 -0.11764706]]


In [7]:
import numpy as np

def lu_decomposition_gauss(A):
    n = A.shape[0]
    # Inisialisasi L sebagai matriks identitas dan U sebagai salinan A
    L = np.eye(n)
    U = A.astype(float)  # Konversi ke float

    for k in range(n-1):  # Eliminasi maju
        for i in range(k+1, n):
            faktor = U[i, k] / U[k, k]
            L[i, k] = faktor
            U[i, k:] -= faktor * U[k, k:]

    return L, U

# Penggunaan contoh dengan matriks baru
A = np.array([[4, 3, 0],
              [6, 3, 7],
              [2, 1, 3]])

L, U = lu_decomposition_gauss(A)
print("L:")
print(L)
print("U:")
print(U)


L:
[[1.         0.         0.        ]
 [1.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
U:
[[ 4.          3.          0.        ]
 [ 0.         -1.5         7.        ]
 [ 0.          0.          0.66666667]]


In [8]:
import numpy as np

def lu_decomposition_crout(A):

    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for j in range(n):
        L[j, j] = 1  # Set diagonal L ke 1
        for i in range(j, n):
            U[j, i] = A[j, i] - np.dot(L[j, :j], U[:j, i])
        for i in range(j+1, n):
            L[i, j] = (A[i, j] - np.dot(L[i, :j], U[:j, j])) / U[j, j]

    return L, U

# Contoh penggunaan:
A = np.array([[4, 2, 0],
              [1, 3, -1],
              [5, 6, 2]])

L, U = lu_decomposition_crout(A)
print("L:")
print(L)
print("U:")
print(U)


L:
[[1.   0.   0.  ]
 [0.25 1.   0.  ]
 [1.25 1.4  1.  ]]
U:
[[ 4.   2.   0. ]
 [ 0.   2.5 -1. ]
 [ 0.   0.   3.4]]
